version: '3'

services:
  frontend:
    build: ./frontend
    container_name: "radiodiodi2019_frontend"
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

  backend:
    build: ./backend
    container_name: "radiodiodi2019_backend"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    command: yarn start

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet